from __future__ import annotations

from typing import Any, Protocol

from ...contracts import AuditEvent, InvestigationRun, OperationalEvent


class InvestigationRuntimeStore(Protocol):
    def create_run(self, run: InvestigationRun, *, dataset_id: str, profile_id: str) -> None: ...
    def get_run(self, tenant_id: str, run_id: str) -> InvestigationRun | None: ...
    def update_run(self, run: InvestigationRun) -> None: ...
    def append_operational_event(self, event: OperationalEvent) -> None: ...
    def append_audit_event(self, event: AuditEvent) -> None: ...
    def put_artifact(self, tenant_id: str, run_id: str, artifact_type: str, payload: dict[str, Any]) -> None: ...
    def get_artifact(self, tenant_id: str, run_id: str, artifact_type: str) -> dict[str, Any] | None: ...
